name: GuardDog for Client

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  guarddog:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    name: Scan dependencies
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 3 # needed to diff the current commit

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install GuardDog
        run: pip install guarddog

      - run: pip install poetry

      # currently, this runs on all dependencies. Some grep-fu necessary to get a requirement.txt-like file containing changes in more recent diff, similar to below:

      # - name: Get diff of changed packages
      #   run: git diff HEAD^ HEAD poetry.lock | grep -Po '[a-zA-Z-\/@.0-9]+@[.0-9\n\r]+' > requirements-diff.txt # this fails with exit code 1 if there is no grep match
      #   working-directory: ./client

      - run: poetry self add poetry-plugin-export
        working-directory: ./client
      - run: poetry export --without-hashes --format=requirements.txt > requirements.txt # only deps in group [main] by default. 
        working-directory: ./client
      - run: guarddog pypi verify requirements.txt --output-format sarif --exclude-rules repository_integrity_mismatch > guarddog.sarif
        working-directory: ./client

      - name: Upload SARIF file to GitHub
        uses: github/codeql-action/upload-sarif@v4
        with:
          category: guarddog-builtin
          sarif_file: ./client/guarddog.sarif
